### ISSUE TITLE
OGG audios

### ISSUE THREAD

**Issue by NoNAT-Telecom** [VolkovLabs/volkovlabs-image-panel#129]
Is there any tutorial for version 5.1.0?

I'm trying to use the tool with OGG audios.

The idea is to check call center call data such as: date and time, time on call, origin, destination and then be able to listen to the audio relating to that call.

I don't think there is anything like that. But it's just an idea.

Thanks to everyone involved

**Comment by mikhail-vl** [comment]
@NoNAT-Telecom We just released 5.1.0 and have not prepared blog post with updates yet.

  OGG audio files are supported as Base64 encoded files or as URL using new multi media options. Please follow previous tutorial: https://www.youtube.com/watch?v=hLMtsCWPOg8

  Let us know if you have any specific issues or questions.
