### ISSUE TITLE
Update migration for old layout

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-image-panel#130]
Feedback from Grafana Review:
```
Having tested it in our testing environment, where I first load a dashboard using 5.1.0 then update the plugin to 5.2.0, all of the dashboard panels render the "no results" message. (Please see attached screenshots.)

The only way to solve this as a user is to edit each panel and add the media source manually in the panel options.
```

**Comment by mikhail-vl** [comment]
@vitPinchuk Old dashboard attached:

[Images-1721393483723.json](https://github.com/user-attachments/files/16312864/Images-1721393483723.json)

**Comment by vitPinchuk** [comment]
@mikhail-vl   

  
The old dashboard should be updated with the correct `pluginVersion` less than 5.2.0. for panels

Keep current migration behavior
