### ISSUE TITLE
Supporting PDF documents more than 2Mb size

### ISSUE THREAD

**Issue by mpiotrowski-pandq** [VolkovLabs/volkovlabs-image-panel#26]
Hi,
I'm trying to load pdf with 7.3MB from postgresql. Result - loaded only frame.
Smaller ones (1-2 MB) from the same table goes smoothly.

BR

**Comment by mikhailredis** [comment]
@mpiotrowski-pandq, it's a great question. I have not tested plugin with big size pdfs.

What kind of browser do you use? Plugin displays PDF using iframe. There is no specification on how big source data can be, every browser may implement it differently. Have you tried with Chrome?

Also, limitation can be in the Grafana's data frames, datasource or PostgreSQL - needs to check that the base64 was retrieved correctly. I have to test various sizes and see where limitation is.

**Comment by mikhailredis** [comment]
@mpiotrowski-pandq, I found the solution. The base64 should be converted to Blog and then displayed according to: https://stackoverflow.com/questions/40674532/how-to-display-base64-encoded-pdf, https://stackoverflow.com/questions/58488416/open-base64-encoded-pdf-file-using-javascript-issue-with-file-size-larger-than

```
var base64 = ("yourBase64StringVariable")
const blob = base64ToBlob( base64, 'application/pdf' );
const url = URL.createObjectURL( blob );
const pdfWindow = window.open("");
pdfWindow.document.write("<iframe width='100%' height='100%' src='" + url + "'></iframe>");

function base64ToBlob( base64, type = "application/octet-stream" ) {
  const binStr = atob( base64 );
  const len = binStr.length;
  const arr = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    arr[ i ] = binStr.charCodeAt( i );
  }
  return new Blob( [ arr ], { type: type } );
}
```

I will try it out and update the plugin.

**Comment by mikhailredis** [comment]
@mpiotrowski-pandq, fix merged and tested on the 13Mb Postgres manual retrieved from Postgres.

I will submit it to Grafana repository tomorrow and it will take a couple of days to approve, meanwhile you can download directly from the repository: https://github.com/VolkovLabs/volkovlabs-image-panel/releases/tag/v2.4.0.

Please let me know if there is anything else.

**Comment by mpiotrowski-pandq** [comment]
@mikhailredis working like a charm. Thanks!

**Comment by fercasjr** [comment]
I know that this was fixed long time ago, but I can't load PDFs bigger than 4 Mb (or so), I'm using postgres 16.2 , Grafana v11.5.2 and the business media plugin 6.2.0, any Idea what I'm doing wrong?.

I tried with the 13 Mb Postgres pdf manual and I't doesn't render. however If I select Image as type (Obviously doesn't load) I can download the file, and open the downloaded file with Acrobat reader and it seems to be normal.

**Comment by mikhail-vl** [comment]
@fercasjr Do you see any errors in the panel or developer console?

**Comment by fercasjr** [comment]
> [@fercasjr](https://github.com/fercasjr) Do you see any errors in the panel or developer console?

developer console, the files that doesnt load have this message in

![Image](https://github.com/user-attachments/assets/b7f71bf5-59b3-4fa0-a6cf-80905470e0fe)

 the console : [Violation] 'message' handler took 1569ms

**Comment by fercasjr** [comment]
I think I'm on the right track I read the following [https://volkovlabs.io/blog/using-grafana-to-display-large-pdf-documents-weve-got-you-covered-4e654e8d4bce/] which pointed me towards using a bytea table. I haven't figured out how to "Upload" the pdf using the Business Input plugin, but I use postgres pgAdmin to load a file using pg_read_binary_file(),  and if I tweak the Query in the Business media plugin as follows:

`SELECT name, encode(img, 'base64') FROM images WHERE name ='$name';`

I can see bigger PDFs. I guess now I need to figure out how to tweak the code in [use](https://volkovlabs.io/blog/form-panel-file-upload-20240310/) on the part where new FileReader() is used; to save the data in bytea instead of being encoded in base64

**Comment by mikhail-vl** [comment]
@fercasjr Look like you are on the right track.
