### ISSUE TITLE
Customize the toolbar of the PDF Viewer by removing the print and save buttons

### ISSUE THREAD

**Issue by CAMILLIER** [VolkovLabs/volkovlabs-image-panel#49]
Hello,

I use this panel in grafana to display PDF files. 
And I would like to know if it is possible to customize the toolbar of the PDF Viewer by removing the print and save buttons. 
The goal is to limit user actions.
I am using Chrome browser

Thank you for your help

**Comment by mikhail-vl** [comment]
@CAMILLIER That's a great question! We use `iframe` to display PDF and looking at available options (https://pdfobject.com/pdf/pdf_open_parameters_acro8.pdf) there is no options to disable just print and save buttons.

  PDF Toolbar can be completely disabled in Chrome browser and this option will be added in #50.
  Let me know if it works for your use-case.

**Comment by mikhail-vl** [comment]
PR is merged and will be a part of the upcoming release later this week.

**Comment by mikhail-vl** [comment]
@CAMILLIER Base64 panel released and submitted to the Grafana team for review: https://github.com/VolkovLabs/volkovlabs-image-panel/releases/download/v3.2.0/volkovlabs-image-panel-3.2.0.zip.md5

  Meanwhile, you can download it directly from GitHub.
  Please let us know if there is anything else.

**Comment by CAMILLIER** [comment]
> @CAMILLIER Base64 panel released and submitted to the Grafana team for review: https://github.com/VolkovLabs/volkovlabs-image-panel/releases/download/v3.2.0/volkovlabs-image-panel-3.2.0.zip.md5
> 
> Meanwhile, you can download it directly from GitHub. Please let us know if there is anything else.

Hello,

I downloaded the new version of the image/video/audio PDF panel 
I installed it and discovered a new option to disable the toolsbar. It works very well

Thank you very much for your help
