### ISSUE TITLE
Setting the panel height

### ISSUE THREAD

**Issue by asafgalili** [VolkovLabs/volkovlabs-image-panel#52]
Hello,
I am using the Base64 image grafana plugin, and it seems great.
Though, I don't understand how the Panel height can be determined.

If I select that the width and height will be by the panel, the image width\height proportions are changed:
![image](https://user-images.githubusercontent.com/31435586/196417976-fdb0436e-84a8-4230-a9d3-8865614ee72b.png)

If I select to have 2 images per line, with the width by the panel with original height the image may override one another, like that:
![image](https://user-images.githubusercontent.com/31435586/196418401-77067868-5998-4d78-8d4f-edd126564f16.png)

What I want to achieve is to have 2 images per line, where the width is by the panel and the panel height will be adjusted per each line by the "heights" image in that line.

for example (forgive me for my bad photoshop abilities):
![image](https://user-images.githubusercontent.com/31435586/196419752-774469cd-5b92-4282-9313-290d6a337c69.png)

Is it possible???

Thanks,
Asaf

**Comment by mikhail-vl** [comment]
@asafgalili Thank you for your questions.

  It would be a nice feature, but plugins can't modify the panel dimensions. Only Dashboard Editors can change the layout of the dashboard.

  You can choose a custom option and get each image's calculated width and height from the data source. It can help to display it correctly in the provided layout.

  Let me know what you come up with. Maybe there is another option we can add to help with your use case.

**Comment by asafgalili** [comment]
Thanks a lot
