### ISSUE TITLE
Support for sanitized variables in URL field

### ISSUE THREAD

**Issue by Here-Be-Dragons** [VolkovLabs/volkovlabs-image-panel#53]
I am using your panel type with the Grafana-native "repeat by variable" functionality, which will duplicate the panel for each entry in an array variable. When you do this using the native "Panel Links" feature in Grafana, you can optionally include the variable name and it will replace the variable name with the value for the given repeated panel.

For instance, if I have a variable:    
```
"myImages": ["image1","image2","image"]
```  
and specify a Panel link:  
```
d/z3PG9iV4z/some-other-dashboard?orgId=1&var-myImages=${myImages}
```
then for each repeated panel, the URL will include the rendered version of the URL, such as:
```
d/z3PG9iV4z/some-other-dashboard?orgId=1&var-myImages=image1
```

As it stands today, each repeated panel simply includes the link with the raw variable name unsubstituted.  There are other panel types, such as [Polystat](https://github.com/grafana/grafana-polystat-panel) that include a "sanitize" option to substitute the values which would be very helpful in the above scenario.

**Comment by mikhail-vl** [comment]
Hello, @Here-Be-Dragons,

  Thank you for the feature request. I can quickly add replace variables functionality for the URL.

**Comment by mikhail-vl** [comment]
@Here-Be-Dragons PR with the feature merged.

  I was planning to update the Grafana toolkit to the latest version and release a new version later this week.

  Please let us know if there is anything else.

**Comment by mikhail-vl** [comment]
@Here-Be-Dragons Base64 Image Panel 3.3.0 released today and submitted to Grafana for review.

  While under review, you can download from the GitHub: https://github.com/VolkovLabs/volkovlabs-image-panel/releases/tag/v3.3.0

  Please let us know if you need anything else.

**Comment by Here-Be-Dragons** [comment]
I can't believe how quickly you turned this change around. Thank you!

**Comment by mikhail-vl** [comment]
@Here-Be-Dragons Thank you! Let us know if there is anything else.

**Comment by mikhail-vl** [comment]
@Here-Be-Dragons The Base64 image panel was updated in the Grafana Catalog today: https://grafana.com/grafana/plugins/volkovlabs-image-panel/
