### ISSUE TITLE
Unable to save dashboard with video panel

### ISSUE THREAD

**Issue by ChinmoyPadhi** [VolkovLabs/volkovlabs-image-panel#57]
Hi,
I'm unable to save the dashboard with the video panel getting the following error on my browser
<img width="907" alt="image" src="https://user-images.githubusercontent.com/14870799/209371766-983b4a80-6c5c-411a-885d-1d735c7f6a62.png">

this is the base64 of my video 
[encoded_video_base64.txt](https://github.com/VolkovLabs/volkovlabs-image-panel/files/10296337/encoded_video_base64.txt)

**Comment by mikhail-vl** [comment]
@ChinmoyPadhi That's a great question! Grafana restricts the dashboard size and can't save it if it's too big.

  Static Data Source keeps data inside the dashboard and looks like it's too big for Grafana to save.
  I suggest using a database, JSON, or any other storage data source to keep it outside the dashboard.

  Let me know if it helps.

**Comment by ChinmoyPadhi** [comment]
Thanks @mikhail-vl for your response
Could you please provide me some link or references how to save this dashboard to database(preferrably, MySQL) or JSON.

Although I tried to copy the JSON using JSON Model from Dashboard Settings option to a Notepad
And later I tried to import the same JSON , I got the same error which my browser is currently complaining.
I need some help if you can guide me in that direction

Here is my json content
[base-64_video_.txt](https://github.com/VolkovLabs/volkovlabs-image-panel/files/10298126/base-64_video_.txt)

**Comment by mikhail-vl** [comment]
@ChinmoyPadhi Dashboard size is limited, and I would not recommend storing big files inside using Static Data Source.

  Please consider using Postgres, Mysql, or any other database/storage to store media files as we explained in the Documentation: https://volkovlabs.io/plugins/volkovlabs-image-panel/datasources/.

**Comment by mikhail-vl** [comment]
@ChinmoyPadhi I hope the documentation cleared out your questions. Based on the community feedback, we added more information in the Data Source section: https://volkovlabs.io/plugins/volkovlabs-image-panel/datasources/.

  Please let us know if there is anything else.
