### ISSUE TITLE
How to use live feed using base64 image panel

### ISSUE THREAD

**Issue by ChinmoyPadhi** [VolkovLabs/volkovlabs-image-panel#58]
Hi,
I have gone through the youtube video, but I didn't find the configurations or is their a way we can use zoom or Microsoft teams

**Comment by mikhail-vl** [comment]
@ChinmoyPadhi As we explained in our videos, we created a live feed based on the images constantly updated in the database and then displayed them using the base64 panel in Grafana.

  The dashboard with the image panel should have refresh settings of 500ms-1s to update periodically.
  Let me know if it's clear.

**Comment by mikhail-vl** [comment]
@ChinmoyPadhi, I did not hear from you. I hope it's clear.

  If not, please let us know.
