### ISSUE TITLE
Display base64 image from MQTT

### ISSUE THREAD

**Issue by tankienleong** [VolkovLabs/volkovlabs-image-panel#63]
Hi @mikhail-vl , is it possible to display base64 image from the MQTT data source? This will be fantastic as we do not need RTSP stream to view the live camera feed.

**Comment by mikhail-vl** [comment]
@tankienleong Base64 panel works with any data source. Let me know if you have any issues.

**Comment by tankienleong** [comment]
@mikhail-vl  The panel shows error nothing to display but my python opencv code is able to display the base64 image. The mosquitto log file also shows sending publish to grafana.

**Comment by mikhail-vl** [comment]
@tankienleong Could you check what you see in the Table view? If you see a base64 encoded image, could you copy it and decode it?

**Comment by mikhail-vl** [comment]
You also may see errors in the Browser Console, which can give an idea what is wrong with the image.

**Comment by tankienleong** [comment]
No data in the Table view.

**Comment by tankienleong** [comment]
![Capture](https://user-images.githubusercontent.com/25731934/223306421-c83432ea-d7f4-4339-80bb-75074fdce350.JPG)
Is there any setup need to be done over here when using MQTT as data source?

**Comment by mikhail-vl** [comment]
@tankienleong If you see no data in the Table view, then no data frames come from the MQTT data source.

   Please verify the data source configuration. You should see a field with an encrypted field and then specify it in the base64 panel to display an image.

**Comment by tankienleong** [comment]
@mikhail-vl  The panel is able to display the image after I put the encoded image in JSON format. 
Thanks for your help.

**Comment by mikhail-vl** [comment]
@tankienleong Is it possible to share a screenshot of your dashboard with the base64 panel? I would like to highlight that panel works with MQTT Data Source in the blog post for the upcoming release.
