### ISSUE TITLE
Toolbar for displaying huge images

### ISSUE THREAD

**Issue by Rumbelstilzchen** [VolkovLabs/volkovlabs-image-panel#69]
Is there some option to have a toolbar to download the image or to zoom in?
Or how to configure the url-field for just having the download?

**Comment by mikhail-vl** [comment]
@Rumbelstilzchen We can do the toolbar to be able to download the image. It's a good idea!

  Regarding zoom-in, it's also possible. I will look into it.

**Comment by mikhail-vl** [comment]
@Rumbelstilzchen We added toolbar with download, zoom and navigation.

  We plan to do release tomorrow, we have a small scaling issue to fix. You are welcome to test fro CI workflow if you want to.

**Comment by mikhail-vl** [comment]
@Rumbelstilzchen Thank you for the feedback.

  Could you please open a separate issue for the zoom & pinch. Is it what you are looking for https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-big-image--big-image ?

  Could you please provide a screenshot to demonstrate the overlay menu weirdness. Are you talking about the ChromeUI in Grafana 9.5 or something else?

  Do you want to see the title on the toolbar? Can you demonstrate what are you looking for and open an issue?

  We can plan to implement both in the upcoming release.

**Comment by mikhail-vl** [comment]
@Rumbelstilzchen We added Pan and Pinch Zoom. It will be a part of the upcoming release.

  Meanwhile, you can download the signed plugin from the CI artifact.

**Comment by Rumbelstilzchen** [comment]
Thank you this is also nice, but (sorry for always having a but :smirk: )

- (Unfortunately I cannot disclose real-live images) Let us assume you have an image of 4000x4000 pixels, a screen width of 1980 pixel. Thus the image is resampled to fit to the display - that is fine.
After zoom in there is no new "resample" and thus the image stays blurry because of the initial "resample".
- As my images are mostly grey-scale plots, The color of +/-/pan is nearly invisible - can you make it configurable?

**Comment by mikhail-vl** [comment]
@Rumbelstilzchen ZoomIn/Out and Reset were moved to the top toolbar next to Download in the latest PR.

  Let us know if there is anything else.

**Comment by Rumbelstilzchen** [comment]
> @Rumbelstilzchen I did a quick test with a 40mpx image which is 8,000x5,400 pixels, I don't see any degradations when zooming in. 

Was your image jpeg? I have png which is definetively bigger than the screen.
Steps I did:
Download the image by the new buttons - zoom in into both downloaded image and within grafana.
Result: image within grafana is very blurry. downloaded image is very sharp and still full of details.
(I could share example via private communication.)

at version 4.0.0 - an item called "times circle" appeared...
![image](https://github.com/VolkovLabs/volkovlabs-image-panel/assets/8233580/6c418fad-704d-4f06-b0b6-d1cea0d4e762)
Btw. I'm forced to stick to grafana 9.2.x (because of a bug in library panels in later versions)
In 10.0.1 it is correctly displayed as an overlay over the image
