### ISSUE TITLE
Image description field

### ISSUE THREAD

**Issue by EvannG1** [VolkovLabs/volkovlabs-image-panel#81]
Hello,

I've just installed this plugin, which suits my needs perfectly.

However, would it be possible to add a description for each image? And that this description could be retrieved from the query.

Let me explain, I'm currently displaying images from a camera, and this camera takes pictures every X minutes and stores them in a database with several fields including the base64 encoded image and a "datetime" field.
Currently, using this plugin, I can display all my images, but I can't tell which image was taken at which time.

Thanks

**Comment by mikhail-vl** [comment]
@EvannG1, how and where would you like the time and description to be displayed?

  We have had a similar request before and can implement it in the upcoming version.

**Comment by EvannG1** [comment]
![image](https://github.com/VolkovLabs/volkovlabs-image-panel/assets/33735118/1825cd98-b065-458b-9ef8-7e9e4bdadd38)

Here's what our old panel looks like, written using JavaScript.
A slider that allows you to go from one image to another (by default to the right to be on the last image captured) and just below the date.

On your plugin, the date can be displayed below the image (centered?), or below the Previous/Next buttons.

**Comment by mikhail-vl** [comment]
@EvannG1 Ok, I will check what is the best option to display the description.
