### ISSUE TITLE
Support for RTSP

### ISSUE THREAD

**Issue by robynb1** [VolkovLabs/volkovlabs-image-panel#85]
Would you consider adding RTSP support to your plugin?

**Comment by mikhail-vl** [comment]
@robynb1 I am not familiar with RTSP. Looking around, it's impossible to display RTSP directly in the browser without converting RTSP to other formats supported in the browser.

  Like this one: https://medium.com/cisco-fpie/how-to-render-rtsp-streams-within-a-react-app-e7957e591075

  We can look into supporting video formats using URLs in the upcoming version.

**Comment by mikhail-vl** [comment]
We discussed this internally and decided that adding a `<video>` element for video streaming is out of the scope of the Base64 plugin.

  There are Community Plugins that support video and may work for video streaming.

**Comment by robynb1** [comment]
:(
