### ISSUE TITLE
Failed to install Plugin

### ISSUE THREAD

**Issue by Narahari-Mengane** [VolkovLabs/volkovlabs-image-panel#87]
I have admin access, also my grafana version is up to date. But unable to install the plugin, what could be the reason?
Attaching the screenshot of my dashboard here.
![111111](https://github.com/VolkovLabs/volkovlabs-image-panel/assets/89959165/4d51c4db-8753-4493-bdec-0bf414c85a07)

**Comment by mikhail-vl** [comment]
@Narahari-Mengane Check the Grafana logs for details. It may be permissions to create plugin's folder or access the archive on grafana.com. It's hard to tell without looking at the logs.
