### ISSUE TITLE
Display of low-res images blurry, no option to change image-rendering mode

### ISSUE THREAD

**Issue by denglerchr** [VolkovLabs/volkovlabs-image-panel#88]
Hello, 
We are trying out your panel in SMS-group for the display of images stored in our database.
It works well, except with extremely lo-resolution images (in the range of 40x50 pixels), where the display seems to interpolate between pixels. You are probably using auto mode for image rendering, see https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering . It would be great to have the option to change the rendering mode if required.

Attached what we have currently vs what we want to display (browser default vs gimp).
![image](https://github.com/VolkovLabs/volkovlabs-image-panel/assets/15248169/d50d7427-bbda-423d-8337-5dd46b324a8a)

**Comment by mikhail-vl** [comment]
@denglerchr Thank you for the feature request.

  It's implemented in the upcoming release.

**Comment by denglerchr** [comment]
Thanks a lot, looking forward to it :)

**Comment by mikhail-vl** [comment]
@denglerchr Plugin was submitted to the Grafana team for review.

  Meanwhile, you can download it from GitHub to test: https://github.com/VolkovLabs/volkovlabs-image-panel/releases/tag/v4.1.0.
